### ISSUE TITLE
Competitiveness issues for ORCA

### ISSUE THREAD

**Issue by Alan-JW** [Soheil-ab/Orca#10]
Hey , @Soheil-ab 

I found some of the following phenomena when using the model,
1、Orca is far less competitive than Cubic.
2、There is also a gap between Orca's competitiveness and Cubic's.

Here are my [concrete results](https://docs.google.com/document/d/1nQb1JQxmmoMf8z2ArmpqbBUM6Inp9oDHYFUJYTuFXok/edit#)

I would like to ask you if you encountered any of the problems I mentioned above during your previous use or testing? If so, how did you solve these problems?

Thank you very much for your answer.

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

Sorry that I won't find enough time to go over all your experiments (at least in the following days), but let me give a few general comments here. I assume that by "competitiveness" you meant TCP-friendliness. If that's the case, then the settings of your experiments can impact the results. For instance, if you choose very large buffer sizes, a throughput-hungry scheme like Cubic can fill up the buffer or if you choose very small buffer, schemes like BBRv1 can become very aggressive too. So, the setting that you choose should somehow reflect practical scenarios. You can find the setting that we used to test TCP-friendliness in the SIGCOMM'20 paper.

**Comment by matthewyuhb** [comment]
Hi @Soheil-ab @Alan-JW 
How can I set up the competing scene with Orca？
I want to run more than one Orca flow at the same time and I set the FLOW_NUM in src/define.h to 2. However, it can't run successfully and reports the error as follows:
![image](https://user-images.githubusercontent.com/46056126/109047431-d6b06a80-7710-11eb-899d-63699122fee9.png)

**Comment by Soheil-ab** [comment]
Hi @matthewyuhb ,

One way to set up TCP-Friendliness tests is that you change the source code (server-side) to make it independent of Mahimahi (e.g. check the discussions here: https://github.com/Soheil-ab/Orca/issues/1). Then, you can use three machines, 2 as servers sending traffic and one as client getting the packets. You can put client behind Mahimahi to be able to control the bufferSize, bottleneck link BW, etc. Then, use the modified server to send traffic using Orca and for instance use iperf to send traffic using Cubic. You can use the same setup and replace the iperf server with another Orca server to test Fairness. (You can refer to the corresponding sections in the Sigcomm'20 paper to see the details of the setups/experiments).

Re your error: the FLOW_NUM should not be changed.  That MACRO was only useful for another project. Here, you can assume that it doesn't exist in the code! Later, if I get free time, I will polish the code ;-)

**Comment by matthewyuhb** [comment]
Thanks so much for your reply!

**Comment by jialianchen** [comment]
@Soheil-ab 
hello! i want to know how to test the TCP-Friendliness.
i have follow the discuss in https://github.com/Soheil-ab/Orca/issues/1 and get the server and  client without  mahimahi.
you said  above that  use three  machines, 2 as servers sending traffic and one as client .
i get confused here.
what should i do to set up my server.
in two server,
the server A in ip_a is  `bash ./orca-standalone-emulation.sh port`
and the server B in different ip (ip_b) is `bash ./orca-standalone-emulation.sh port`
what should i do to use the client?
the default commant is `sudo ./rl-module/client server_ip flow_id server_port`
so what server_ip should i use?ip_a?ip_b?
it seems that  no matter what ip i choose ,no competive on  the link

**Comment by Soheil-ab** [comment]
Hi @jialianchen,
You need to remember that any flow has two sides and for generating it you need to bring up two entities. 
In the current code, any instance of "client" will request **a** flow from the specified server_ip (and port). So, in your scenario, you need to make **two** connections by running **two** separate client commands with two different server_ip/ports.
