### ISSUE TITLE
Orca's performance in the 5G wireless scenario and new training proposal

### ISSUE THREAD

**Issue by ktxu1224** [Soheil-ab/Orca#11]
Dear Soheil,
Have you ever tested the Orca in the 5G wireless scenario where bandwidth changes quickly and unpredictablely and How Orca perform in the aforementioned scenario? The second question is whether we can train Orca in the new unseen environment to enhance the performance in new scenario while perform inference to guide the classic cc ? In another word，I want to train the Orca in real time between two MTPs(Monitoring Time Period) and infer at the MTP, How do you think of this proposal?

Many thanks!
Best regards,
Eric

**Comment by Soheil-ab** [comment]
Hi @ktxu1224 

Regarding your 1st question:
We didn't have access to 5G traces, so we haven't tested it on 5G yet. 

Regarding your 2nd question:
Yes, why not? You can train your own Orca if you like! 
Do not see Orca as "a" TCP scheme, instead, see it as a framework that you can use to build your own CC on top of classic CCs that you choose (potentially the ones that work good in your specific scenario). 

That said, you may also be interested in DeepCC, our new design that targets cellular networks titled: "Wanna Make Your TCP Scheme Great for Cellular Networks? Let Machines Do It for You!" 
<available here: [https://doi.org/10.1109/JSAC.2020.3036958]>
 
Hope that helps

**Comment by ktxu1224** [comment]
Thanks for your reply! @Soheil-ab

Regarding training Orca,  the first question is would you like to share your own training  dataset? Or Can you give some suggestions for making the dataset about 5G network if it is not feasible to share your own dataset? 

And the second is, in a practical scenario where multiple connections coexist, each connection needs to run a model and may have different network state,  do you think it is reasonable if we use the data of each connection to fine-tune the same offline trained model online and then apply the model to each connection ?

 Many thanks!
Best regards,
Eric

**Comment by Soheil-ab** [comment]
Hey @ktxu1224 

1.1- I didn't quite get what you mean by dataset. Dataset is a valid term when there is a (sort of) supervised learning. If you read the paper, you will see that Orca uses Reinforcement Learning in which the learning happens live on the environments. 
1.2- As I said, we didn't use 5G (either trace files or real network) to train or test Orca. If you have access to such traces, you need to use them for your training sessions. (In case you have access to such traces, we welcome if you can share it with us (and others)) :-)
1.3- In case you meant our 4G traces used in the evaluation section, the link to these traces (gathered in NYC) is already in the paper. You can find them here: https://github.com/Soheil-ab/Cellular-Traces-NYC

2- That actually makes sense and is currently a direction in the online learning. That means you start with a good offline model and later to improve the model, on top of the offline model, you perform online learning tricks to adjust the model.
