### ISSUE TITLE
How can I control the length of MTP?

### ISSUE THREAD

**Issue by matthewyuhb** [Soheil-ab/Orca#12]
Hi, @Soheil-ab .
Thanks for sharing the work. Lately I've been reading the paper and the source code. However I have not found which parameter controls the Monitoring Time Period.  Could you show me  which part of the code controls the MTP accurately?
Thanks!

**Comment by Soheil-ab** [comment]
Hey @matthewyuhb 
Please Checkout: 
https://github.com/Soheil-ab/Orca/blob/7205628ddcfdefe9f2b37aa47fa2bcf3b7f61ab7/src/orca-server-mahimahi.cc#L442

BTW, you may also need to change some other polling delay parameters in the c and python codes accordingly.

Hope that helps.
