### ISSUE TITLE
A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases

### ISSUE THREAD

**Issue by TJU-solide** [Soheil-ab/Orca#14]
Sorry to interrupt，I want to test the throughput of No-model and the throughput of Clean-Slate Model in the same network environment as the sample code, how should I modify it based on the sample code? Looking forward to your answer, thanks!

**Comment by Soheil-ab** [comment]
Hey @YSuolide 

If by No-Model you meant Orca before training, you can simply start a training session and let the learned model be saved after only a few steps. Then, simply close the training session and use your saved model (which is just basically a no-model!) during the evaluation.

Regarding Clean-Slate, you will need a Kernel patch that gives you this functionality, but currently this part is not included in this version of the release. If I find some free time, I may polish that part of the patch and push it to rep later.

**Comment by TJU-solide** [comment]
NO-model I mean to observe the effect of ORCA model optimization in the same network environment without using ORCA model. By the way, if I want to test the effect of other models mentioned in the paper, such as C2TCP, Aurora, etc., how can I modify the code or what can I do? Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月1日(星期六) 凌晨5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
Hey @YSuolide
 
If by No-Model you meant Orca before training, you can simply start a training session and let the learned model be saved after only a few steps. Then, simply close the training session and use your saved model (which is just basically a no-model!) during the evaluation.
 
Regarding Clean-Slate, you will need a Kernel patch that gives you this functionality, but currently this part is not included in this version of the release. If I find some free time, I may polish that part of the patch and push it to rep later.

**Comment by Soheil-ab** [comment]
@YSuolide ,

Orca without any model means Cubic! So, you can simply use Cubic. But, if you still wanna keep all Orca's structure including its state collection from the Kernel, etc, you can do this: comment the line in the c code where Orca applies the action to the Kernel. That way, all Orca's overhead is still there, but no action will be enforced to the Kernel!

Re C2TCP: the current Kernel already includes DeepCC and C2TCP's patches. So, you can follow the instructions [here](https://github.com/Soheil-ab/c2tcp) and [here,](https://github.com/Soheil-ab/DeepCC.v1.0) to evaluate C2TCP and DeepCC. 

Re Aurora: you need to ask its authors!

**Comment by TJU-solide** [comment]
hi,Because my understanding of the ORCA code leaves something to be desired. And I am not very good at understanding the role of Mahimahi and the workflow. The final log file in the Orca code records the size of the throughput, and I want to do an experiment to test the throughput of the default congestion control algorithm without deep reinforcement learning decisions, how should I do it? Can I just remove the part of the .c file that calls py from the stratserve function? Do I need to remove the code in other locations or what should I do?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 晚上6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
@YSuolide ,
 
Orca without any model means Cubic! So, you can simply use Cubic. But, if you still wanna keep all Orca's structure including its state collection from the Kernel, etc, you can do this: comment the line in the c code where Orca applies the action to the Kernel. That way, all Orca's overhead is still there, but no action will be enforced to the Kernel!
 
Re C2TCP: the current Kernel already includes DeepCC and C2TCP's patches. So, you can follow the instructions here and here, to evaluate C2TCP and DeepCC.
 
Re Aurora: you need to ask its authors!

**Comment by Soheil-ab** [comment]
Hey @YSuolide ,

I already told you one way of doing that!

Another way is to comment the line 308 (controller thread) of the server : 
https://github.com/Soheil-ab/Orca/blob/master/src/orca-server-mahimahi.cc#L308

G.L

**Comment by TJU-solide** [comment]
I get it! Thank you so much, I'm really sorry to bother you in the middle of a busy day, and I appreciate your patience in replying, thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 凌晨4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
Hey @YSuolide ,
 
I already told you one way of doing that!
 
Another way is to comment the line 308 (controller thread) of the server :
 https://github.com/Soheil-ab/Orca/blob/master/src/orca-server-mahimahi.cc#L308
 
G.L

**Comment by TJU-solide** [comment]
Hey! One more small question, I see that you have implemented other congestion control algorithms such as BBR in your kernel, which parameter should I change if I want to change the underlying congestion control algorithm? Sorry for the many interruptions, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 凌晨4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
Hey @YSuolide ,
 
I already told you one way of doing that!
 
Another way is to comment the line 308 (controller thread) of the server :
 https://github.com/Soheil-ab/Orca/blob/master/src/orca-server-mahimahi.cc#L308
 
G.L

**Comment by Soheil-ab** [comment]
@YSuolide,

You need to change _**scheme_**_ parameter to the desired scheme. Remember that not all TCP schemes can coexist with Orca. Checkout the discussion section of the Sigcom'20 paper for more info.

BTW, you need to first enable that scheme in the Kernel through sysctl command. You can find different tutorials about that on the web.

**Comment by TJU-solide** [comment]
Thank you very much for your answer, I don't quite understand what the sysctl command is used to start? Forgive me for not knowing much about the kernel implementation. Also, when I turn off the reinforcement learning module control, I can get good throughput with reno and cubic, but with BBR it works fine, but the throughput is less than 5%, which is hard for me to understand, is it my operation? I would like to get your reply, thank you very much!


Translated with www.DeepL.com/Translator (free version)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
@YSuolide,
 
You need to change **scheme**_ parameter to the desired scheme. Remember that not all TCP schemes can coexist with Orca. Checkout the discussion section of the Sigcom'20 paper for more info.
 
BTW, you need to first enable that scheme in the Kernel through sysctl command. You can find different tutorials about that on the web.

**Comment by TJU-solide** [comment]
This is the result of my query on the kernel congestion control algorithm.



sysctl net.ipv4.tcp_available_congestion_control


net.ipv4.tcp_available_congestion_control = cubic reno bbr bic cdg dctcp westwood highspeed hybla htcp vegas nv veno scalable lp yeah illinois



However, when I change the scheme parameter to dctcp, the following error occurs.



/home/suolide/桌面/test/Orca-master/rl-module/orca-server-mahimahi 44444 /home/suolide/桌面/test/Orca-master/rl-module 20 4 dctcp 0 wired192 wired96 100 orca-dctcp-wired192-wired96-100-20-6400 30 6400 0


[orca-server-mahimahi.cc-start_server-141] TCP congestion doesn't exist: Operation not permitted



I don't know what's wrong with me and I hope to get your help. I'm very sorry for the many times I've interrupted.
By the way, I can't find the manual of mahimahi on the official website, if you have the information, can you share it with me? Thank you very much!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
@YSuolide,
 
You need to change **scheme**_ parameter to the desired scheme. Remember that not all TCP schemes can coexist with Orca. Checkout the discussion section of the Sigcom'20 paper for more info.
 
BTW, you need to first enable that scheme in the Kernel through sysctl command. You can find different tutorials about that on the web.

**Comment by Soheil-ab** [comment]
Hey @YSuolide ,

I saw your message today accidentally! For a faster response, plz next time mention me in your question ;)
Regarding DCTCP, there are two notes. First, DCTCP requires ECN from the network, but the emulator that we use doesn't support ECN. So, at the end of the day, even if you switch to DCTCP, you won't get any meaningful results. Second, to see if you can set your congestion control to any desired one, try to do it manually first. You can do something like: sudo sysctl -w net.ipv4.tcp_congestion_control=dctcp
If there is no issue you should see that your cc has been changed.

**Comment by TJU-solide** [comment]
Hi, sorry to bother you again
After I successfully placed the client and serve side on different VMs (without mahimahi), the log file of the serve side has some errors, as shown below, how should I solve this problem? I look forward to your reply, thank you very much!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
Hey @YSuolide ,
 
I saw your message today accidentally! For a faster response, plz next time mention me in your question ;)
 Regarding DCTCP, there are two notes. First, DCTCP requires ECN from the network, but the emulator that we use doesn't support ECN. So, at the end of the day, even if you switch to DCTCP, you won't get any meaningful results. Second, to see if you can set your congestion control to any desired one, try to do it manually first. You can do something like: sudo sysctl -w net.ipv4.tcp_congestion_control=dctcp
 If there is no issue you should see that your cc has been changed.

**Comment by Soheil-ab** [comment]
I see no log files attached!

**Comment by TJU-solide** [comment]
Hi, I would like to ask how I should proceed if I want to deploy server side and client side separately on different hosts and want one server to interact with multiple clients?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soheil-ab/Orca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 凌晨0:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Soheil-ab/Orca] A question about reproducing throughput experiments in the Clean-Slate Model and No-Model cases (#14)





 
I see no log files attached!
