### ISSUE TITLE
Some questions about running and version switching

### ISSUE THREAD

**Issue by weidehui** [Soheil-ab/Orca#15]
@Soheil-ab Sorry to bother you, I'm a beginner. I am having some difficulties in running and would like to ask for your help. I followed the step-by-step installation as described in the code. However, when running the sample test, the problem of "no process found" appears as shown in the figure below.
![image](https://user-images.githubusercontent.com/40263901/120925176-f7be2980-c709-11eb-8258-b83e3aff6a2f.png)
![image](https://user-images.githubusercontent.com/40263901/120925182-03a9eb80-c70a-11eb-97f1-51a3d8b7837c.png)
I have tried many ways to solve it, and my colleagues also encounter the same problem. Although the questions may be fool, I hope to get your help.
One more question, I read in your paper that you have also implemented a purely DRL-based version. I wonder how to switch to this version. I see that the reward in the GYM_Env_Wrapper function in envwrapper.py is fixed to 10. So I'm not sure if I switch from here? Looking forward to your help, thanks!

**Comment by Soheil-ab** [comment]
Hi @weidehui ,

Re your errors: Actually the messages that you see are normal and you should not consider them errors! If you check actor.sh script, you will see that we try to kill different processes at the end of the script (There are some reasons for that but I skip going too much into the details here). 

What you should check is whether you have proper results after running the emulations. How to check that? If you take a look at Line 40 actor.sh ([here](https://github.com/Soheil-ab/Orca/blob/cafaf9a31cb63a5b8754e1f410776d35b8ce47d0/actor.sh#L40)) you'll see that the final results are gathered in rl-module/log/sum-* files (the exact name depends on the parameters that you choose for the emulations). If you see errors on the result file, then there were problems. If not, everything ran smoothly!

Re ur next question, you need another Kernel Patch for running Clean-Slate version. 
However, the kernel patch required for running Clean-Slate RL is not included in this release. So, unfortunately you won't be able to run that part at least for now. 
I'm not sure when I'll get enough time to cleanup that Patch and make it ready for a public release.

**Comment by weidehui** [comment]
@Soheil-ab Thank you very much for your reply! I checked the log file and found that it was a "Permission denied" problem. I hope later users can refer to it. 
I'm sorry I have one more question. I want to know how to change the adjustment interval of DRL. I see a lot of "sleep" intervals in the code. I don't know whether to change one of the sleeps or somewhere else. I am also curious what the limit of this interval is, whether it is related to the time of inference or for some other consideration. Thank you again for your reply to my questions！

**Comment by Soheil-ab** [comment]
@weidehui , 

Re change of MTP (or report period), there are two main places that you should take a look at: orca-mahimhahi-server.cc and envwrapper.py
 
As you will find out there is a variable called report_period that can be changed on c code. The rule of thumb is that, if you wanna go below 10ms, you should have at least two time faster loop in the python code (get_state funvtion) to make sure you don't miss any report from the c code.
 
there diff. implementation issues that can limit the MTP: e.g. generally, sleep function (timers) in python is (are) not that accurate, so you cannot go below some values! As another example, retrieving new info from kernel will face some intrinsic delays that will limit you too.

**Comment by weidehui** [comment]
@Soheil-ab 
Thank you very much!

**Comment by diulehenduo** [comment]
> @Soheil-ab Thank you very much for your reply! I checked the log file and found that it was a "Permission denied" problem. I hope later users can refer to it. I'm sorry I have one more question. I want to know how to change the adjustment interval of DRL. I see a lot of "sleep" intervals in the code. I don't know whether to change one of the sleeps or somewhere else. I am also curious what the limit of this interval is, whether it is related to the time of inference or for some other consideration. Thank you again for your reply to my questions！

@weidehui Hello, how you fix the Permission denied problem?
