### ISSUE TITLE
the question about the patching Orca's Kernel

### ISSUE THREAD

**Issue by jialianchen** [Soheil-ab/Orca#16]
Hello,i try to use your algorithm,but i meet some difficulties when i try to patching Orca's Kernels follow the option 1.
i use ubuntu 14.04 in tencnet cloud  and my linux kernels is 3.13.0-128-generic.
my /etc/default/grub is 
```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
#GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
#GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX_DEFAULT="crashkernel=1800M-4G:128M,4G-:168M panic=5"
GRUB_CMDLINE_LINUX="console=ttyS0,9600n8 console=tty0"
GRUB_SERIAL_COMMAND="serial --speed=9600 --unit=0 --word=8 --parity=no --stop=1"

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console
GRUB_TERMINAL="console serial"

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
GRUB_RECORDFAIL_TIM
EOUT=5
GRUB_GFXPAYLOAD_LINUX=text
```
i can successfully perform the first two steps but after i reboot
i get
![351625059049_ pic](https://user-images.githubusercontent.com/38684111/123985410-0988a900-d9f8-11eb-883a-3686026a4aeb.jpg)
it really troubled me for a long time, I don’t know whether you could give me some suggestions.
thanks for your help!

**Comment by Soheil-ab** [comment]
Hi @jialianchen,

An empty /proc/modules may indicate that no modules are loaded. That means something went wrong during the installation of the new kernels. You may wanna try to generate the kernel configuration again after installing Orca's Kernel. Something like:
 
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
 
A better option is to install grub-customizer and move the new installed kernel to the **top** of the list. Then after saving the setting, the app will enforce a new grub configuration. 

sudo add-apt-repository ppa:danielrichter2007/grub-customizer
sudo apt-get update
sudo apt-get install grub-customizer
sudo grub-customizer

Also, every cloud provider has some tutorials about how to change the kernel on their systems. So you may wanna look at your cloud provider's instructions too.

**Comment by jialianchen** [comment]
thans for your help!@Soheil-ab 
but it still  bothers me....
i can successfully install other kernels and use it like linux 4.13.0  but i can't install orca`s kernels just as i mentioned above.
and i have use
```
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
```
but it don`t solve the problem.
![WeChatc7ab0587160c8771ac4b6d1775b61833](https://user-images.githubusercontent.com/38684111/124085996-31711e80-da83-11eb-919b-47ac330fc162.png)
i guess it is not a difficult problem,but it borher me...
i want to know which cloud server provider and which configuration you used.i would use the same provider and configuration as yours ,in this way i think i can easily use your algorithm....

**Comment by Soheil-ab** [comment]
@jialianchen ,

I have a simple suggestion for you. Orca is a **sender side** framework. That means Orca's Kernel is only required to be installed on the **sender** side. 
So, you can use a **local** server/pc, that you have full control over it, and install Orca's kernel there. That local server will be the source of the traffic for you. Then, you can leave all other clients' Kernels intact! Simply use Vanilla Ubuntu kernels on your remote servers. Those remote servers will play the role of the receivers in your testbed. 

BTW, you can find the details of our in-field tests including the name of providers in section 5.1 of our SIGCOMM'20 paper ([here](https://dl.acm.org/doi/10.1145/3387514.3405892))

**Comment by jialianchen** [comment]
thanks for your help!
i can easily install the kernel when i use the local pc.
thanks!
