### ISSUE TITLE
the question about the  integrate into Pantheon

### ISSUE THREAD

**Issue by jialianchen** [Soheil-ab/Orca#17]
Hello ,i want to  integrate orca into Pantheon,but i meet some questions.
i just comment the mahimahi and the client part in orca-server-mahimahi.cc(152-155,243)  as the sender,and use client as before.
but when i use them  in Pantheon,i get confused result.
[pantheon_report.pdf](https://github.com/Soheil-ab/Orca/files/6777370/pantheon_report.pdf)
it seems it can't run correctly,but i can run outside the Pantheon  successfully.
i noticed that you said in issues before that you had plan to integrate it to Pantheon.
i wonder whether there are some easily ways to  integrate it and where is my method wrong.
thanks for your help!

**Comment by Soheil-ab** [comment]
Hi @jialianchen 

Unfortunately, I haven't got the time for officially releasing a version working with Pantheon yet. 

However, to give you my brief comment here: 
The throughput graph in your report file tells me that (most likely) you are not pointing to the correct **checkpoint directory**. iow, the agent (most likely) doesn't use the **provided trained model** and starts from some random weights. So, make sure that you are passing all Orca's required arguments (similar to the actor/server scripts in Orca) correctly when you use Pantheon or any other frameworks.

**Comment by han0602** [comment]
> Hello ,i want to integrate orca into Pantheon,but i meet some questions. i just comment the mahimahi and the client part in orca-server-mahimahi.cc(152-155,243) as the sender,and use client as before. but when i use them in Pantheon,i get confused result. [pantheon_report.pdf](https://github.com/Soheil-ab/Orca/files/6777370/pantheon_report.pdf) it seems it can't run correctly,but i can run outside the Pantheon successfully. i noticed that you said in issues before that you had plan to integrate it to Pantheon. i wonder whether there are some easily ways to integrate it and where is my method wrong. thanks for your help!

Hi @jialianchen， Thanks for raising this question—it's exactly what I was wondering about as well!

I've been following your recent work, especially your progress in the ZiXia project, and it seems like you've already addressed this issue there. Would you be open to sharing some guidance or suggestions on how you approached it? Any tips or insights would be greatly appreciated!

Thanks in advance!
