### ISSUE TITLE
How can I start a 6 hour training process 

### ISSUE THREAD

**Issue by matthewyuhb** [Soheil-ab/Orca#19]
Hi @Soheil-ab ,
I want to evaluate Orca's performance by tuning the parameters of the reward function so I need to re-train the DRL model. I followed the intruction and ran the "./orca.sh 4 44444"  and "./orca.sh 1 44444" commands to achieve that goal.  However, I didn't found there are new checkpoints derived in /models and there are no new content in the rl-module/log/sum-*.

Could you please inform me that is there anything wrong with my procedure ？What's more, how can I ensure that the training process is  running smoothly?

**Comment by Soheil-ab** [comment]
Hi @matthewyuhb ,
If you cannot run <./orca.sh 4 44444>, then most likely you haven't installed the required packages, etc. yet. 
Before doing any training, I suggest that you try to run a simple evaluation. When you're done with that then try to explore the training scripts. The <./orca.sh 1 44444> command should start a simple training session (from scratch). You need to change the hyper parameters, number of actors, etc, before running your own version of training though. Also, you may need to have a proper machine/cluster if you're thinking about training your own Orca for a wide range of environments. 

Re monitoring your training session: I suggest that you bring up Tensorboard and use it to visualize the session and some general desired stuff like return, critic/policy loss, etc.
