### ISSUE TITLE
Questions about shared memory

### ISSUE THREAD

**Issue by weidehui** [Soheil-ab/Orca#20]
Hello, @Soheil-ab , sorry to bother you. I'm having some problems with shared memory. I refer to your program and try to use shared memory to communicate between C and Python. But my program crashes after a while, removing the shared memory does not. I did a lot of experiments and modifications, but still did not solve the problem or find the cause. I don't know if you have encountered this problem. Looking forward to your help, thank you very much!

**Comment by Soheil-ab** [comment]
Hi @weidehui,

I assume that you're not referring to our code, right?! 
Although we haven't faced any crashes to the shared mem, I have a few suggestions in case you wanna use the shared memory concept to com. b.w. **your** C and Python code.  
1- Try to create a simple test program to see if you are doing things correctly. Then, on top of that expand your logic. 
2- Make sure that you're not writing/reading outside of the created shared memory and you have not permission issues to access the memory.
3-  Use "ipcs" command to monitor the shared memory's state.

**Comment by weidehui** [comment]
Thank you very much, we will try!
