### ISSUE TITLE
Reproducing the overhead experiment result in the paper

### ISSUE THREAD

**Issue by tianhan4** [Soheil-ab/Orca#21]
In Figure. 10 in the Orca paper. I find the overhead of Orca is significantly lower than Aurora. 
However, running Orca means running the Cubic and RL model at the same time, while Aurora only runs the RL model to adjust the CWND window. How can I achieve the low overhead of Orca? With smaller model architecture or longer MTP? Didn't get a clue from the paper.

**Comment by Soheil-ab** [comment]
@tianhan4,

There are multiple things involved here:
1- There is a trade-off b.w. the overhead and the performance (e.g., check fig 11). The change of MTP value manifests itself in that trade-off.
2- Having a classic design such as Cubic helps to reduce the overall overhead of the system, b.c. parts of the control logic (fine-grain actions) have been delegated to it. 
3- The monitoring part (and enforcing the final action) of Orca is already implemented in the Kernel. 

So, it's not abt whether a scheme runs an RL model, it's abt **how** it does it! 

Hope that helps.
For a faster response, next time plz tag me on the question.
