### ISSUE TITLE
Congestion Window Update Rule

### ISSUE THREAD

**Issue by giacomoni** [Soheil-ab/Orca#22]
Hi,

from the server's code, it looks like the congestion window is updated in two instances:

1) In slow start, increasing the window by a factor 1.1
2) Congestion avoidance, using:
              target_ratio=atoi(alpha)*orca_info.cwnd/100;
              
In the second case, how does the update rule relate to the window increase presented in the paper, i.e. 2^(alpha) * cwnd?

Thanks for the clarification.

**Comment by Soheil-ab** [comment]
Hi @giacomoni,

The alpha you're referring to on the C code is basically the final coefficient that will be applied to the current cwnd of the system.
The calculation of the 2^(alpha)   (-2<alpha<2) already happened on the python code! Check the envwrapper.py and d5.py scripts for the details. 

https://github.com/Soheil-ab/Orca/blob/master/rl-module/envwrapper.py
https://github.com/Soheil-ab/Orca/blob/master/rl-module/d5.py

Also, pay attention that there is a subtle conversion here. The alpha given to the C code is already scaled up 100x. So, when applied, the final cwnd will be scaled down 100x!
