### ISSUE TITLE
How can I only get the cwnd output of DRL?

### ISSUE THREAD

**Issue by halcyonway** [Soheil-ab/Orca#23]
Hi, I wanna test Orca in my transport protocol.
My system has transport function and integrated cubic. I only need the output of Orca DRL module.
So could you tell me how can I run DRL solely and the input&output formation/position of it?

Thanks a lot :)

**Comment by Soheil-ab** [comment]
Hi @peijl1998,

The current release does not include the Clean-Slate version (Assuming by "run DRL solely" you mean Orca without the classic TCP scheme (i.e., the Clean-Slate version presented in the SIGCOMM'20 paper)).
