### ISSUE TITLE
Questions about training traces

### ISSUE THREAD

**Issue by chenxi-yang** [Soheil-ab/Orca#27]
Hi,

I am trying to reproduce the training of Orca. In the paper, you mentioned that there are 256 actors. May I ask what traces are these actors use separately? Is there a script guiding the trace usage of different actors? Thanks

Best,
Chenxi

**Comment by Soheil-ab** [comment]
Hi @chenxi-yang, 

Table 2 of SIGCOMM'20 paper indicates the corresponding environments of all actors during the training.
re the script, if you meant the orchestrator (see [here](https://github.com/Soheil-ab/Orca/issues/25)), unfortunately it was not ready for the public release.

**Comment by chenxi-yang** [comment]
Hi,

Thanks for the reply. After reviewing the Table 2, I am still a bit confused about the trace setting. For the environment for each actor, did you randomly pick one fixed bandwidth, min RTT, and buffer size? That is, is each environment's parameter fixed or they fluctuate?

Thanks,
Chenxi

**Comment by Soheil-ab** [comment]
Hi @chenxi-yang,
We experimented with different approaches, but if I remember correctly, the model provided here is the result of training over fixed predetermined environments from a kind of uniform dist.

**Comment by chenxi-yang** [comment]
Thank you.
