### ISSUE TITLE
How to collect data without mahimahi？

### ISSUE THREAD

**Issue by diulehenduo** [Soheil-ab/Orca#29]
Hi， @Soheil-ab 
I annotated the relevant code according to the discussion #1 , and planned to use the mininet simulation node to run it, using h1 and h2 as the receiver and sender to run the server and client respectively. Finally, it ran successfully, but I don't know how to collect the relevant data of the network. , such as throughput, queue delay, etc. This sounds stupid, but I still want to ask you for advice.

**Comment by Soheil-ab** [comment]
Hi @diulehenduo ,
Since this is a general question, I suggest that you take a look at the [mininet's documentations](https://github.com/mininet/mininet/wiki/Documentation)
