### ISSUE TITLE
Any help to integrate into Pantheon?

### ISSUE THREAD

**Issue by hexi519** [Soheil-ab/Orca#3]
In the paper ,it seems Orca used Pantheon for test,so is there any help for integration with Pantheon ,like wrapper.py for Pantheon?
Thanks a lot !

**Comment by Soheil-ab** [comment]
Hey @hexi519,

Currently we don't have a _release_ version on top of Pantheon. I plan to work on a release (if I get enough time!)

{Just for the record: Correct, as mentioned in the paper, we used some tools from Pantheon but we modified the source code ... }
