### ISSUE TITLE
What are the $bdp$ and $qs$ for the step-10s-3-level trace?

### ISSUE THREAD

**Issue by chenxi-yang** [Soheil-ab/Orca#31]
Hi Soheil,

I am trying to reproduce the Figure 1 in the paper. Should I use the 'step-10s-3-level ' as the trace file? 

https://github.com/Soheil-ab/Orca/blob/cafaf9a31cb63a5b8754e1f410776d35b8ce47d0/orca-standalone-emulation.sh#L31 shows that we need to set $bdp$ and $qs$ when setting up the actor based on the given trace's bandwidth. However, 'step-10s-3-level ' does not have a fixed bandwidth. May I ask what the $bdp$ and $qs$ are you used to generate Figure 1's evaluation?

Thank you very much!
Chenxi

**Comment by Soheil-ab** [comment]
Hi @chenxi-yang,
Simply uncomment lines 35 to 37 to have the step-scenario of Figure 1. It was mentioned [here!](https://github.com/Soheil-ab/Orca/blob/cafaf9a31cb63a5b8754e1f410776d35b8ce47d0/orca-standalone-emulation.sh#L34).

p.s. When you set qs manually, you don't need bdp anymore (as it was only used in that script to set the queue size automatically)
