### ISSUE TITLE
Ubuntu Version Required.

### ISSUE THREAD

**Issue by Paul-Georgeee** [Soheil-ab/Orca#32]
Hi, I am trying to install Orca in Ubuntu 16.04 using VMware. After patching kernel(There only some unusual outputs :" Hmm. There is a symbolic link /lib/modules/4.13.1-0521-learner/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/4.13.1-0521-learner/build". )
In fact, I don't know what happened but then I reboot. It can not successfully reboot and output many "do_IRQ: 0.103 No irq handler for vector". I can not find some solutions.

**Comment by Soheil-ab** [comment]
Hi, 
You can use updated versions of those patches from the [Sage Project](https://github.com/Soheil-ab/sage) <with Ubuntu 16.04 as base>:
Check out [here](https://github.com/Soheil-ab/sage/tree/main/linux-patch)
