### ISSUE TITLE
Is the sending rate in Orca paper the ingress or egress?

### ISSUE THREAD

**Issue by chenxi-yang** [Soheil-ab/Orca#33]
Hi,

Orca's scripts use `mm-thr` on `down-link-log` to generate a bandwidth utilization figure including capcity, traffic ingress and traffic egress. However, there is one line in Orca's Figure 1. May I ask which line you used for the sending rate representation in the main paper? Should it be traffic egress as egress is the departure pattern from the server? We find that the traffic egress never exceeds the bandwith upper bound (while Figure 1's sending rate sometimes is above the pink area). Wonder if I misunderstand the plots.

Thank you very much!

Best,
Chenxi

**Comment by Soheil-ab** [comment]
Hi

- To begin, it's important to distinguish between some common terms. Typically, 'server' and 'client' don't always correspond to 'sender' and 'receiver'. For example, in a typical <iperf> scenario, the server is actually the receiver, and the client is the sender! So, to avoid confusion, I'll refer to them as sender and receiver.

- In networks, links are bi-directional, meaning the perspective from which you view an abstracted queue determines its egress and ingress sides. Imagine a simple connection where the sender is on the left, the queue in the middle, and the receiver on the right. Traffic sent from the sender to the receiver makes the left side of the queue the ingress and the right side the egress.
(S) ---- (uni-dir link L1) ------>------  (Q)  -------- (uni-dir link L2) ------> -------- (R)

- With an adequately sized buffer and a larger bandwidth (BW) for L1 compared to L2's bandwidth, it's possible for the ingress rate to occasionally exceed L2's bandwidth.

- Observing egress rates higher than the actual bandwidth of L2 in this scenario will be simply defying physics!

I hope this explanation clarifies the sending rates depicted in Orca's Fig. 1.
