### ISSUE TITLE
Some questions about orca-server-mahimahi.cc

### ISSUE THREAD

**Issue by Alan-JW** [Soheil-ab/Orca#4]
Hello, thank you very much for your contribution to the community. Here I would like to ask you a question. What is the purpose of setting target_ratio=1.1*orca_info for each time in the slow startup stage?
It seems that you did not mention this in your paper.
Thank you very much for your answer.

Here is the corresponding code snippet, 

 if(!slow_start_passed)
                    {
                        //got_no_zero=1;
                        tcp_info_pre=orca_info;
                        t0=timestamp();

                        target_ratio=1.1*orca_info.cwnd;
                        ret1 = setsockopt(sock_for_cnt[i], IPPROTO_TCP,TCP_CWND, &target_ratio,sizeof(target_ratio));
                        if(ret1<0)
                        {
                           DBGPRINT(0,0,"setsockopt: for index:%d flow_index:%d ... %s (ret1:%d)\n",i,          flow_index,strerror(errno),ret1);
                           return((void *)0);
                        }

**Comment by Alan-JW** [comment]
@Soheil-ab

**Comment by Soheil-ab** [comment]
Hey @Alan-JW ,

Good question! Before handing the control to Orca, we add another 10% increase steps on cwnd during slow-start phase to increase the chance of observing a higher maximum value for the throughput. That will help later, when normalized values of throughput (normalized to the maximum seen so far) are fed to the system. 

Hope that it answers your question. Please let me know if you have any other questions.

**Comment by Alan-JW** [comment]
Thank you very much for your answer. What do you mean by "increase the chance of observing a higher maximum value for the throughput"?
@Soheil-ab

**Comment by Soheil-ab** [comment]
@Alan-JW ,

The throughput that a user observes/gains relates to (at least) the number of competing flows in the network. Therefore, the maximum throughput that a user observes can vary based on the number of competing flows and the specific CC protocol that they use. IOW, also the maximum achievable throughput for a user is capped by the bottleneck link bandwidth, the user may or may not achieve that value. 

That said, the 10%-increased-steps during the slow-start phase, increases the chance of observing a higher (gained) throughput (temporarily). And this will lead to the increase in "the chance of observing a higher maximum value for the throughput".
