### ISSUE TITLE
how to get the network data

### ISSUE THREAD

**Issue by jialianchen** [Soheil-ab/Orca#5]
Hello ,i have the question about the network data.
In define.h
![83A2DD3E-D0E5-45EF-8E7D-EEF01E04DA74](https://user-images.githubusercontent.com/38684111/99560666-14f70900-2a01-11eb-86b5-28a04a570130.png)
You define "#define TCP_ORCA_INFO 46 ",
I check the socket.h,46 means SO_BUSY_POLL
"#define SO_BUSY_POLL		46"
I can not understand how use "getsockopt( sk, SOL_TCP, TCP_ORCA_INFO, (void *)info, (socklen_t *)&tcp_info_length );"
get the data of info.
 Maybe the question is very silly , i am sorry for that:)

**Comment by Soheil-ab** [comment]
Hey @jialianchen 

You are looking at a wrong file for the definition of the TCP Socket Options! You can find the existing definitions for Kernel 4.13.1 here {lines 90-121}: <https://elixir.bootlin.com/linux/v4.13.1/source/include/uapi/linux/tcp.h>
As you will see, 46 is not reserved!

For more details, you can check out our provided kernel patch file: Orca/linux/linux-4-13-1-orca-0521+c2tcp.patch
You will find out that we patch the file "include/uapi/linux/tcp.h" starting at line 210 and add new TCP_DEEPCC_INFO socket option at line 233.

BTW, be sure that there is nothing called a silly question out there! Questions are either 1) answered ones or 2) unanswered ones!  & your question is now an answered one :-)
