### ISSUE TITLE
Can client separately run on non-Orca-built kernel?

### ISSUE THREAD

**Issue by meng-tong** [Soheil-ab/Orca#9]
Hi, I'm trying to run Orca in remote mode without Mahimahi.
I have a dumb question here: it seems that the client (compiled from client.c) is a simple receiving/acknowledging tool. So and it run on a linux kernel without Orca patched?
Thanks!
@Soheil-ab

**Comment by Soheil-ab** [comment]
Hey @meng-tong 

Correct. As mentioned in the paper, Orca is a sender-side TCP. That means it only requires change at the sender side and as long as the client sends back Acks, the client can use any TCP protocol (on any Kernel, e.g. without Orca patch).
